server:
  port: 8086
spring:
  redis:
    host: 192.168.26.130
dubbo:
  application:
    name: shop_order
  registry:
    address: zookeeper://192.168.26.130:2181
    consumer:
      check: false
      timeout: 1000